---
title: "aula_citation"
author: "Amanda"
date: "14/02/2020"
output:
csl: ../citation/nature.csl
bibliography: ../citation/AED.bib
abstract: Tentando aprender a usar o rmarkdown, me ajuda Senhô! 
---

# Usando o Rmarkdown para bibliografia
1. Em nosso gerenciador de referencias geramos um arquivo .bib com as referencias utilizadas no relatorio; 
2. Incluimos esse arquivo no projeto que estamos trabalhos, de preferencia em uma pasta chamada citation/bibliografia etc;
3. Nessa mesma pasta colocamos um arquivo csl (citation style) com o estilo de citação que gostariamos de ter em nosso relatorio (acredito que exista um padrão de citação do markdown, mas nao tenho certeza entao usei o csl da ecology);
4. No YAML do relatorio colocamos os caminhos para os arquivos: Em bibliography colocamos o caminho para o arquivo de .bib que precisamos. 
Em csl o estilo da citação que queremos.
5. Abrimos no R o arquivo .bib para que seja possivel copiar o @ do artigo para o corpo do texto do relatorio (deve ter uma forma mais fácil pq assim parece trabalhoso demais, mas fiz assim e funcionou);
6. Exemplo: no arquivo .bib a primeira info que aparece do artigo é:
@article{smac_prefeitura_2014, 
copiamos tudo após a chave para o corpo do texto: @smac_prefeitura_2014 
Assim o rmd vai compreender que voce quer a referencia desse artigo no fim do seu arquivo de relatorio;


# Gestão de bibliografia 

BibTex são arquivo de texto com formato .bib feito por quem fez o LaTex. As citações tem chave de citação com o tipo de trabalho o nome e o ano que chamamos no arquivo de texto. Indicamos no YAML (cabeçalho) bibliografia: arquivo de bibliografia.bib 


Em bibliography colocamos o caminho para o arquivo de .bib que precisamos. 
Em csl o estilo da citação que queremos. 

Exemplo:
A análise exploratória de dados é essencial @tukey_exploratory_1977

## Exportando para word e colocando o template desejado

Formata o arquivo word com o estilo que você quer e salva. Colocando como reference_citation e o nome do arquivo que tem o template.

1. Salvar na pasta docs do projeto o arquivo formatado com o template desejado, daí é só colocar esse caminho:

*output:
  word_document: 
    reference_docx: ../docs/template_capitulos.docx*

2. Daí é só knitar em formato word e pronto! - (ainda nao consegui criar meu proprio template entao utilizei o fornecido em aula). 

## Colocando output da análise no markdown
Primeiramente alguns comandos básicos de chunks: 
include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
message = FALSE prevents messages that are generated by code from appearing in the finished file.
warning = FALSE prevents warnings that are generated by code from appearing in the finished.
fig.cap = "..." adds a caption to graphical results.

1. Adicionamos um chunk e colocamos echo = false 
2. Colocamos tudo necessario para que a analise seja rodada como foi feito no script, pacotes, caminho da planilha, criação de objetos etc. 
3. Daí é só rodar que o output da analise aparece no markdown (porém, fica bem feio no word, deve haver como formatar).

# References
